sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '4'
script:
  - npm run test
  - npm run check-coverage
before_install:
  - npm i -g npm@^3.0.0
before_script:
  - npm prune
after_success:
  - npm run report-coverage
  - npm run semantic-release
branches:
  only:
    - master
